### ISSUE TITLE
Favicon is blurry for no reason

### ISSUE THREAD

**Issue by oldmud0** [BuildandShoot/buildandshoot.github.io#3]
Even the 16x16 one is very blurry. This was the original one:

![Original 16x16 favicon](https://cloud.githubusercontent.com/assets/5247009/26754499/9c36e48a-4841-11e7-9782-549e06ad37c1.png)

**Comment by NateShoffner** [comment]
Fixed in f08730a9da0b142ed68688494b4e768779e6dedf.
