### ISSUE TITLE
The forum is gone?!

### ISSUE THREAD

**Issue by thegreatestminer** [BuildandShoot/buildandshoot.github.io#9]
When you try to access the forum, (https://www.buildandshoot.com/forums) it just redirects you back the homepage.

Is there a new link for the forums?

**Comment by Kuunikal** [comment]
They are under maintenance. You can access the maintenance page here:

https://buildandshoot.github.io/forums/

**Comment by xtreme8000** [comment]
Some admin said it would be back yesterday/today, but it still isn't.

**Comment by NateShoffner** [comment]
Forums are back online - https://www.buildandshoot.com/forums/viewtopic.php?f=2&t=14099&p=154724
